version: "3.8"
services:
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_CONN_STR=${REDIS_CONN_STR}
      - SQL_CONN_STR=${SQL_CONN_STR}
      - BLOB_CONN_STR=${BLOB_CONN_STR}
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
